// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	dto "inforce-task/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetOwnerships provides a mock function with given fields: id
func (_m *Service) GetOwnerships(id string) (map[string]interface{}, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetOwnerships")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (map[string]interface{}, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTraits provides a mock function with given fields: body
func (_m *Service) GetTraits(body dto.CollectionTrait) (map[string]interface{}, error) {
	ret := _m.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for GetTraits")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.CollectionTrait) (map[string]interface{}, error)); ok {
		return rf(body)
	}
	if rf, ok := ret.Get(0).(func(dto.CollectionTrait) map[string]interface{}); ok {
		r0 = rf(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(dto.CollectionTrait) error); ok {
		r1 = rf(body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
